name: TestPlugin
version: 1
author: Luca Archidiacono
main: org.spigotmc.tutorial.Main
commands:
  dragon:
    description: You always dreamed to see a dragon? Here is your chance.
    usage: /dragon
  swordandpotato:
    description: Diamond Sword? Sorry for the long speech here is a potato.
    usage: /swordandpotato
  createmagicstick:
      description: You wanna have the magic Stick from Gandalf! Here it is.
      usage: /createmagicstick